Auto complete
philiptober/rapid-git pull request #18
Opened 2016-10-16 16:35 UTC by mhoyer

Please check contained 83070605aa51c4f63a8a117c4f1f4c2348324b26. Not sure why the ```IFS``` variable needs to be set there at all and if it breaks anything prefixing it with ```local```. I bet you possibly corrupted other auto completion libraries accidentally. See also ```-W``` parameter for ```complete``` command: https://www.gnu.org/software/bash/manual/html_node/Programmable-Completion-Builtins.html

2016-10-16 23:06 UTC, agross requested changes

2016-10-16 23:06 UTC, agross commented on rapid-git.sh
> +complete -F _rapid_complete rapid
`complete` is not available on zsh

2016-10-16 23:06 UTC, agross commented on rapid-git.sh
> +complete -F _rapid_complete rapid
Perhaps you put the whole function definition in a conditional `_rapid_zsh`?

2016-10-17 12:03 UTC, agross commented on rapid-git.sh
> +    local cmds="branch checkout diff drop merge push rebase remove stage status track unstage"
DRY, these can be detected. See `__rapid_command_not_found`.

2016-10-18 09:40 UTC, agross commented on rapid-git.sh
> +      local IFS=$'\n'
Should be fixed in master

2024-11-25 18:14 UTC, GregOnNet commented
Hey, what is the state of this PR?
Can it be merged? It looks like Marcel added fixes as requested. :-)

2024-11-25 18:17 UTC, agross commented
State is the same as 8 years ago. I think both of us didn't look at it any more.

2024-11-25 18:21 UTC, closed without merging